# Generated by Django 4.2.3 on 2023-07-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.IntegerField()),
                ('profit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profitReceiver', models.CharField(max_length=42)),
                ('url', models.URLField(blank=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(upload_to='')),
                ('chosen1', models.ImageField(blank=True, upload_to='')),
                ('chosen2', models.ImageField(blank=True, upload_to='')),
                ('chosen3', models.ImageField(blank=True, upload_to='')),
                ('chosen4', models.ImageField(blank=True, upload_to='')),
                ('book_file', models.FileField(upload_to='')),
                ('Arweave', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BinaryField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.PositiveIntegerField()),
                ('seller', models.CharField(max_length=42)),
            ],
        ),
    ]
