# Generated by Django 3.2.6 on 2023-06-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Ohara_Protocol', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amount',
        ),
    ]
