# Generated by Django 3.2.6 on 2023-06-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('The_Ohara_Protocol', '0002_delete_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.IntegerField()),
                ('profit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('url', models.URLField(blank=True)),
                ('intro', models.TextField(blank=True)),
                ('cover', models.ImageField(upload_to='covers/')),
                ('chosen1', models.ImageField(blank=True, upload_to='chosen/')),
                ('chosen2', models.ImageField(blank=True, upload_to='chosen/')),
                ('chosen3', models.ImageField(blank=True, upload_to='chosen/')),
                ('chosen4', models.ImageField(blank=True, upload_to='chosen/')),
                ('book_file', models.FileField(upload_to='books/')),
            ],
        ),
    ]
