# Generated by Django 4.2.2 on 2023-06-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Ohara_Protocol', '0004_auto_20230625_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tx_id',
            field=models.CharField(default='00000000000000000000000', max_length=43),
            preserve_default=False,
        ),
    ]
